---
name: release
on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pre-compile GitHub extension
        uses: cli/gh-extension-precompile@v1.2.1
        with:
          go_version: "1.19"
